#-*version: '3'
services:
  backend:
    image: "${CONTAINER_REGISTRY_ENDPOINT}/image1-backend:${TAG:-latest}"
    container_name: backend
    ports:
      - "8007:8007"
    restart: always

  frontend:
    image: "${CONTAINER_REGISTRY_ENDPOINT}/image1-frontend:${TAG:-latest}"
    container_name: frontend
    ports:
      - "8001:8001"
    depends_on: 
      - backend 
    restart: always
