name: Docker Image CI and Deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          username: nologin
          password: ${{ secrets.SCALEWAY_API_KEY }}
          registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}

      - name: Build the Docker image
        run: docker build . -t ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/jcredo:${{ github.sha }}

      - name: Push the Docker Image
        run: docker push ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/jcredo:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Récupérer la dernière version de l'image depuis le registre
            docker pull ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/jcredo:${{ github.sha }} || exit 1
            
            # Arrêter et supprimer le conteneur existant (si nécessaire)
            docker stop jcredo || true
            docker rm jcredo || true
            
            # Lancer le nouveau conteneur
            docker run -d --name jcredo -p 8020:8020 ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/jcredo:${{ github.sha }}
