name: Docker Image CI and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Build the backend Docker image
        run: |
          docker-compose build backend
          docker images  # List images to confirm build success

      - name: Tag the backend Docker image
        run: docker tag backend:latest ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/image1-backend:latest

      - name: Push the backend Docker image
        run: docker push ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/image1-backend:latest
