name: Docker Image CI and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Job 1: Build and push backend image
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          username: nologin
          password: ${{ secrets.SCALEWAY_API_KEY }}
          registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}

      - name: Build the backend Docker image
        run: docker-compose build backend

      - name: Tag the backend Docker image
        run: docker tag backend ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/credo-backend:${{ github.sha }}

      - name: Push the backend Docker image
        run: docker push ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/credo-backend:${{ github.sha }}

  # Job 2: Build and push frontend image
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          username: nologin
          password: ${{ secrets.SCALEWAY_API_KEY }}
          registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}

      - name: Build the frontend Docker image
        run: docker-compose build frontend

      - name: Tag the frontend Docker image
        run: docker tag frontend ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/credo-frontend:${{ github.sha }}

      - name: Push the frontend Docker image
        run: docker push ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/credo-frontend:${{ github.sha }}

  # Job 3: Deploy the backend and frontend to the remote instance
  deploy:
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy docker-compose.yml to the server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./docker-compose.yml"
          target: "/home/${{ secrets.SSH_USER }}/app"

      - name: Deploy to instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to the directory with docker-compose.yml
            cd /home/${{ secrets.SSH_USER }}/app
            
            # Pull the latest images from Scaleway registry
            docker-compose pull || exit 1
            
            # Stop and remove the old containers
            docker-compose down || true
            
            # Start the new containers
            docker-compose up -d
